-- @metapackage
-- @description rrx
-- @author Richard Cook
-- @version 0.05
-- @about
--  rrx&mdash;Richard's REAPER Extensions
--  * [Tempo mapping](https://github.com/rcook/ReaScripts/blob/main/rrx/rrx_TEMPO_MAPPING.md)
-- @changelog
--  Fixed paths on macOS/Linux
--  Sort menu items by description
-- @provides
--  [data] rrx_TEMPO_MAPPING.md
--  [main] rrx_DeleteAllTempoTimeSigMarkers.lua
--  [main] rrx_GenerateConfigFiles.lua
--  [main] rrx_MarkMeasure.lua
--  [main] rrx_MarkMeasure_1_4.lua
--  [main] rrx_MarkMeasure_2_4.lua
--  [main] rrx_MarkMeasure_3_4.lua
--  [main] rrx_MarkMeasure_4_4.lua
--  [main] rrx_MarkMeasure_5_4.lua
--  [main] rrx_MarkMeasure_6_8.lua
--  [main] rrx_SetTimebasesForTempoMapping.lua
--  [nomain] rrx.lua
