-- @metapackage
-- @description rrx
-- @author Richard Cook
-- @version 0.07
-- @about
--  rrx&mdash;Richard's REAPER Extensions
-- @changelog
--  Removes broken link from About information
-- @provides
--  [main] rrx_DeleteAllTempoTimeSigMarkers.lua
--  [main] rrx_MarkMeasure.lua
--  [main] rrx_MarkMeasure_1_4.lua
--  [main] rrx_MarkMeasure_2_4.lua
--  [main] rrx_MarkMeasure_3_4.lua
--  [main] rrx_MarkMeasure_4_4.lua
--  [main] rrx_MarkMeasure_5_4.lua
--  [main] rrx_MarkMeasure_6_8.lua
--  [main] rrx_SetTimebasesForTempoMapping.lua
--  [nomain] rrx-lib.lua
