-- @metapackage
-- @description Tempo Mapping
-- @author Richard Cook
-- @version 0.00
-- @about
--  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam enim ante, condimentum in
--  maximus sed, pellentesque non est. Suspendisse sagittis justo eu tortor dignissim, non laoreet
--  lacus dictum. Aenean sodales ligula ante, id dapibus diam dapibus ac. Donec at dui consequat,
--  congue neque et, viverra ex. Integer eu massa quis sapien laoreet consequat ultrices quis
--  tortor. Fusce vel semper felis, at maximus mi. Nunc tellus elit, congue sed rhoncus vitae,
--  vestibulum vel sapien. Proin sapien est, commodo at commodo in, volutpat vitae leo. Maecenas
--  facilisis, quam sagittis pretium fringilla, mauris ex interdum dolor, sit amet ultrices dolor
--  odio vel tortor. Curabitur vestibulum lectus tincidunt felis fermentum malesuada. Aenean
--  commodo magna ac est fringilla, tempus ullamcorper eros mollis. Etiam sit amet mi arcu. Fusce
--  nec convallis metus. Nulla at tempus nisi, non varius mauris.
-- @changelog
--  Initial release
-- @provides
--  [main] rcook_Delete_All_Project_Tempo_Time_Sig_Markers.lua
--  [main] rcook_Mark_Measure.lua
--  [main] rcook_Mark_Measure_1_4.lua
--  [main] rcook_Mark_Measure_2_4.lua
--  [main] rcook_Mark_Measure_3_4.lua
--  [main] rcook_Mark_Measure_4_4.lua
--  [main] rcook_Mark_Measure_5_4.lua
--  [main] rcook_Mark_Measure_6_8.lua
--  [main] rcook_Set_Project_Timebases.lua
--  [nomain] rcook_Tempo_Mapping.lua
